### PR TITLE
Update App.js

### PR DESCRIPTION
**Pull request by pooja16111998**
First commit on pooja79760 repo.

### CODE REVIEW

**Comment by pooja16111998** [comment]
pls yeh waale changes pull kr lio

**Comment by MohitR1999** [comment]
Arey kuch dhang ka toh likhti lol 😆

**Comment by pooja16111998** [comment]
Arey pls na ek merge nhi kr skta tu hdd h

**Comment by pooja16111998** [comment]
Mereko dekhna h merge hone pr kya hota h

**Comment by MohitR1999** [comment]
chal theek hai kar rha hu merge 🤣

**Pull request merged**
